### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by tinygrox**
Hope it won't cause any trouble. :)

### CODE REVIEW

**Comment by KSP-TaxiService** [comment]
:x: [Build CommNetConstellation 1.5.2-97-develop failed](https://ci.appveyor.com/project/KSP-TaxiService/commnetconstellation/builds/30858668) (commit https://github.com/KSP-TaxiService/CommNetConstellation/commit/66baf860c2 by @tinygrox)

**Comment by KSP-TaxiService** [comment]
:x: [Build CommNetConstellation 1.5.2-98-develop failed](https://ci.appveyor.com/project/KSP-TaxiService/commnetconstellation/builds/30858843) (commit https://github.com/KSP-TaxiService/CommNetConstellation/commit/04f2a01fe3 by @tinygrox)

**Comment by KSP-TaxiService** [comment]
:x: [Build CommNetConstellation 1.5.2-99-develop failed](https://ci.appveyor.com/project/KSP-TaxiService/commnetconstellation/builds/30858847) (commit https://github.com/KSP-TaxiService/CommNetConstellation/commit/03feacf1f5 by @tinygrox)

**Comment by KSP-TaxiService** [comment]
:x: [Build CommNetConstellation 1.5.2-100-develop failed](https://ci.appveyor.com/project/KSP-TaxiService/commnetconstellation/builds/30858918) (commit https://github.com/KSP-TaxiService/CommNetConstellation/commit/f860413517 by @tinygrox)

**Comment by tinygrox** [comment]
What's happening?

**Comment by KSP-TaxiService** [comment]
Hi @tinygrox,

Please discard the automatic build bot ([message](https://ci.appveyor.com/project/KSP-TaxiService/commnetconstellation/builds/30858918)) of this CNC repository. 😃 

This bot was trying to open my password-protected KSP-DLL zip in your fork environment without a secured password maintained in your fork environment.

I will review and test your localization in this weekend, like I did with your RemoteTech pull request.

Thanks for your contribution!

**Comment by tinygrox** [comment]
Have a nice weekend!😃

**Pull request merged**
