### PR TITLE
Rename small UI *.png files to *.truecolor

### PR DESCRIPTION
**Pull request by cake-pie**
Prevents mipmapping when GameDatabase loads the textures, which subsequently leads to blurry UI when graphics settings are not at full texture quality.

*.png @ quarter res 
blur

*.truecolor @ quarter res
sharp

### CODE REVIEW

**Comment by KSP-TaxiService** [comment]
:x: [Build CommNetConstellation 1.3.2-58-develop failed](https://ci.appveyor.com/project/KSP-TaxiService/commnetconstellation/builds/24306023) (commit https://github.com/KSP-TaxiService/CommNetConstellation/commit/f1806cfc52 by @cake-pie)

**Comment by KSP-TaxiService** [comment]
TIL there is a way to prevent Unity from screwing up my texture resolution. Thanks for letting me know!

Unfortunately, it doesn't work on the Sprite create button, as shown below.
image

I will accept your contribution first and try to resolve the remaining blurry issue.

**Comment by cake-pie** [comment]
> try to resolve the remaining blurry issue.

There's actually another way which is to disable mipmapping in the GameDatabase, that is more involved. I'm actually about to create a new repo for a mod to do that and push some code.

Not sure if that approach would help your situation, but if you hold off on a bit on a release we can investigate further.

**Comment by cake-pie** [comment]
At a very brief glance I see you have some utility functions to create new `Texture2D`s.

1. You need to use the version of the ctor that has `mipmap` and make sure to turn that off. [example](https://github.com/cake-pie/CommunityTraitIcons/blob/master/Source/KerbalTraitSetting.cs#L23)

2. Note that if you are creating textures you need to be mindful to dispose them when no longer used. They apparently [do not get GC'd](https://forum.kerbalspaceprogram.com/index.php?/topic/172665-toolbar-buttons-are-fuzzy-in-141/&tab=comments#comment-3360500).

I'll take a closer look at your code later, but for now you can give the above suggestion a shot.

**Comment by KSP-TaxiService** [comment]
Noted on the texture information.

I remember I found another way to make an image button with single texture some time after initial mod release, without the messy workaround of one "background" texture for each active, normal, highlight or disabled button state. I need to backtrace on how I arrive at this way.

**Pull request merged**
